/** Declaration file generated by dts-gen */

export const routerActionTypes: {
  CHANGE: string;
  GOTO: string;
  REPLACE: string;
  START: string;
};

export function createRouterMiddleware(history: any): any;

export function routerReducer(...args: any[]): any;

export namespace createRouterMiddleware {
  const prototype: {};
}

export namespace routerActionCreators {
  function change(location: any): any;

  function replace(pathname: any): any;

  function start(): any;

  namespace change {
    const prototype: {};
  }

  namespace replace {
    const prototype: {};
  }

  namespace start {
    const prototype: {};
  }
}

export namespace routerReducer {
  const prototype: {};
}
